[project]
name = "example_project"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = ["database_core", "database_util", "models", "migrations", "environments"]

[build-system]
requires = ["uv_build>=0.11.18,<0.12"]
build-backend = "uv_build"

[tool.uv.sources]
copier-template = {path = "..", editable = true}
database_core = {workspace = true}
database_util = {workspace = true}
models = {workspace = true}
migrations = {workspace = true}
environments = {workspace = true}

[tool.uv.workspace]
members = ["database/database_core", "database/database_util", "database/models", "database/migrations", "database/environments"]

[dependency-groups]
dev = ["copier>=9.15.1", "inflection>=0.5.1", "pytest>=9.1.1", "tomlkit>=0.15.0", "typer>=0.26.6", "skylos>=4.29.0", "debugpy>=1.8.21", "alembic>=1.18.4", "sqlalchemy>=2.0.50", "sqlmodel>=0.0.38", "pytest-alembic>=0.12.1", "pydantic-settings>=2.14.1", "psycopg[binary]>=3.3.4", "ruff>=0.15.15", "sqlacodegen>=4.0.3", "sqlglot>=30.12.0"]
