"""auto

Revision ID: e2c6363ccfac
Revises: 546a0bb854f0
Create Date: 2026-06-09 15:21:55.516264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e2c6363ccfac"
down_revision: Union[str, Sequence[str], None] = "546a0bb854f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column(
            "join_date",
            sa.Date(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name="users_pkey"),
        sa.UniqueConstraint("username", name="users_username_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
