"""auto

Revision ID: 74412bbb5201
Revises: e2c6363ccfac
Create Date: 2026-06-09 15:50:44.888241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "74412bbb5201"
down_revision: Union[str, Sequence[str], None] = "e2c6363ccfac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
