"""initial

Revision ID: c218e16ccb64
Revises: 
Create Date: 2026-09-24 11:50:53.033352

"""
from collections.abc import Sequence

from database_util.utils import run_backfill

revision: str = 'c218e16ccb64'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
