"""initial

Revision ID: fc5314db98f7
Revises: 
Create Date: 2026-09-23 16:52:21.920972

"""
from collections.abc import Sequence

from database_util.utils import run_backfill

revision: str = 'fc5314db98f7'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
