"""initial

Revision ID: 0fc7c64c8dc6
Revises: 
Create Date: 2026-08-14 12:34:57.771034

"""
from collections.abc import Sequence

from database_util.utils import run_backfill

revision: str = '0fc7c64c8dc6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
