"""initial

Revision ID: 619c6478955f
Revises: 
Create Date: 2026-09-24 11:41:36.478822

"""
from collections.abc import Sequence

from database_util.utils import run_backfill

revision: str = '619c6478955f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
