"""auto

Revision ID: cfd5e03ea824
Revises: af7d410623b3
Create Date: 2026-08-01 18:06:17.922073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfd5e03ea824'
down_revision: Union[str, Sequence[str], None] = 'af7d410623b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foobar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foobar')
    # ### end Alembic commands ###
