"""auto

Revision ID: 2b26244da010
Revises: 4d320e613918
Create Date: 2026-08-05 13:34:59.601746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from database_util.utils import run_backfill


revision: str = '2b26244da010'
down_revision: Union[str, Sequence[str], None] = '4d320e613918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_modified_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
