"""auto

Revision ID: d33af56a3275
Revises: 2b26244da010
Create Date: 2026-08-05 13:59:36.043245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from database_util.utils import run_backfill


revision: str = 'd33af56a3275'
down_revision: Union[str, Sequence[str], None] = '2b26244da010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey')
    )
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
