"""auto

Revision ID: f13f4ddf6ad0
Revises: d33af56a3275
Create Date: 2026-08-05 14:56:23.410030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database_util.utils import run_backfill


revision: str = 'f13f4ddf6ad0'
down_revision: Union[str, Sequence[str], None] = 'd33af56a3275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_modified_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('orders_user_id_fkey')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
