"""initial

Revision ID: 2a7d456bae34
Revises:
Create Date: 2026-08-06 12:24:06.697441

"""

from collections.abc import Sequence

from database_util.utils import run_backfill

revision: str = "2a7d456bae34"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    run_backfill(revision)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
