"""initial

Revision ID: 8629164201c0
Revises: 
Create Date: 2026-08-04 14:20:04.439231

"""
from typing import Sequence, Union

from database_util.utils import run_backfill


revision: str = '8629164201c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
