"""auto

Revision ID: 4d320e613918
Revises: 8629164201c0
Create Date: 2026-08-05 13:11:42.055086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database_util.utils import run_backfill


revision: str = '4d320e613918'
down_revision: Union[str, Sequence[str], None] = '8629164201c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('join_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
    run_backfill(revision)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
