name: alembic-cicd

on:
  push:

concurrency:
  group: alembic-cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  model-generation:
    name: Model Generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - run: uv sync
      - run: uv run python -m models g

  migrations:
    name: Migration
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - run: uv sync
      - run: uv run python -m migrations cicd

  model-generation:
    name: Model Generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - run: uv sync
      - run: uv run python - models rg

  drift-check:
    name: Drift Check (main)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - run: uv python install
      - run: uv sync
      - run: uv run python -m migrations cicd --no-commit
